apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: wordpress-site
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50